name: Plugin
version: '1.0.0'
author: "ElSus"
main: pr.cubicdev.plugin.Plugin
api-version: '1.20'
commands:
  chestlock:
    description: Comando principal
    usage: /chestlock
    permission: chestlock.command.main
